### ISSUE TITLE
Cryptic "Pending kernel update" message on Linode-based images

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/infra#575]
We use this [packer template](https://github.com/freeCodeCamp/infra/tree/main/packer/linode) to build an image for all instances we provision on Linode.

But, once the instance is created (provisioned from the machine image created by the config above), an annoying interactive prompt seems to break further '`apt` install' of any package.

I am getting an unrelated "Pending kernel update" message like so:

<img width="1056" alt="image" src="https://github.com/freeCodeCamp/infra/assets/1884376/622330bd-5a6c-4964-9330-d031d3cb4e2c">

You can obviously accept the prompt and the packages install just fine.

This breaks much of the ad-hoc scripting, like installing a tool from `apt` and starting up services. I need to research and fix this.

Additional Details :

- Restarting the machine like the prompt suggests doesn't solve the issue.
- Can't uninstall the `needsrestart` package, which shows the prompt, because we depend on it elsewhere.

**Comment by lloydchang** [comment]
this may help
```
sed -i "s/#\$nrconf{kernelhints} = -1;/\$nrconf{kernelhints} = -1;/g" /etc/needrestart/needrestart.conf
```
https://askubuntu.com/a/1424249

**Comment by raisedadead** [comment]
Thanks, but I am not looking to suppress the symptom here :)

**Comment by lloydchang** [comment]
fwiw

my 2 cents :)

> Pending kernel update

looks normal to me after `upgrade: dist`, which can upgrade the kernel because `dist-upgrade` [intelligently handles changing dependencies with new versions of packages](https://askubuntu.com/questions/81585/what-is-dist-upgrade-and-why-does-it-upgrade-more-than-upgrade)

hence
https://github.com/freeCodeCamp/infra/commit/7324c9c60230b73b38e44790a424b470743e9d79
> `upgrade: yes`

lgtm as a workaround

**Comment by lgarber-akamai** [comment]
Hi there!

When provisioning instances with the Linode API, official distribution images will typically default to using the image's kernel (through GRUB 2) while custom images (snapshot/upload) will default to using the latest Linode kernel.

Generally, I think the best approach to this issue is to provision Linodes with the boot config explicitly set to use GRUB 2:

When deploying a machine image created with Packer to a Linode instance, you can create a new [config profile](https://www.linode.com/docs/api/linode-instances/#configuration-profile-create) with the `kernel` attribute set to `linode/grub2`. If you're using IaC tooling, you can automate this process fairly easily (for example, see the [Linode Terraform provider documentation](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#linode-instance-with-explicit-configs-and-disks)).

Alternatively you can create the instance with `booted` set to false, update the implicitly created config, and boot the instance.

**Comment by lloydchang** [comment]
@lgarber-akamai

just curious:

it seems:

> best approach

would shift accountability for maintaining the image from Linode to users

Don't most users prefer Linode official distro images because they already passed Linode's Security, QA, etc. testing?

**Comment by raisedadead** [comment]
Thanks, @lgarber-akamai - It finally makes sense to me now. Yes – We have been using IaC, and here is a sample config: 

https://github.com/freeCodeCamp/infra/blob/f647ab0442c14731095b67aa57914e21072d8483/terraform/ops-test/main.tf#L54

The idea is to bake a golden image, spin the instance and add any workload-specific tooling with Ansible or ad-hoc commands. That's where I saw the difference in the "kernel" between other clouds and Linode. 

We bake our image from a base image off of Linode's `linode/ubuntu22.04` image for example, but I am guessing that makes it "custom", which defaults to the linode's version kernel.

I'll add the https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_config#kernel prop to `linode/grub2` and test it out.

I've been struggling with this for a while - thanks for pointing me in the right direction.

P.S.: For my future self, the list of kernels is available via the CLI with `linode kernels ls` - but we probably never need to change it.
